In [ ]:
'''
np.hstack
np.vstack
np.sort
'''

In [1]:
import numpy as np

In [4]:
a = np.round(10*np.random.rand(2,2))
a

array([[4., 2.],
       [6., 7.]])

In [9]:
b = np.round(10*np.random.rand(2,3))
b

array([[ 1.,  1.,  8.],
       [ 4., 10.,  2.]])

In [11]:
## Using hstack to concat to variable
c = np.hstack((a, b))
c

array([[ 4.,  2.,  1.,  1.,  8.],
       [ 6.,  7.,  4., 10.,  2.]])

In [12]:
A = np.random.permutation(np.arange(10))

In [16]:
## A sorting
A.sort()
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
## A on Descending Sorting
A = A[::-1]
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])